// OpenLayers
import Map from "ol/Map.js";
import View from "ol/View.js";
import VectorLayer from "ol/layer/Vector.js";
import WebGLTileLayer from "ol/layer/WebGLTile.js";
import { fromLonLat } from "ol/proj.js";
import GeoTIFF from "ol/source/GeoTIFF.js";
import VectorSource from "ol/source/Vector.js";

// Other modules
import proj4 from "proj4";
import { register } from "ol/proj/proj4.js";



// ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
// OpenLayers map initialization
// ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

// We define EPSG:3794 (otherwise OL gets confused)
proj4.defs(
    "EPSG:3794",
    "+proj=tmerc +lat_0=0 +lon_0=15 +k=0.9999 " +
    "+x_0=500000 +y_0=-5000000 " +
    "+ellps=GRS80 +units=m +no_defs"
);
register(proj4);

// Where the per-layer manifest lives. It's generated by
// scripts/generateLayersManifest.mjs from whatever files sit in
// public/data/layers2D — see that script for details.
const LAYERS_MANIFEST_URL = "/data/layers2D/manifest.json";
const LAYERS_BASE_URL = "/data/layers2D/";

async function fetchLayersManifest() {
    const response = await fetch(LAYERS_MANIFEST_URL);
    if (!response.ok) {
        throw new Error(`Could not load layers manifest (${response.status})`);
    }
    return response.json();
}

// One WebGLTileLayer per manifest entry. Layers start hidden; the caller
// decides which one(s) to reveal.
function buildRasterLayer(entry) {
    console.log(`buildRasterLayer: Creating layer for ${entry.id} (${entry.filename})`);
    
    try {
        const layer = new WebGLTileLayer({
            source: new GeoTIFF({
                sources: [
                    {
                        url: `${LAYERS_BASE_URL}${entry.filename}`,
                        normalize: false,
                    },
                ],
            }),
            preload: Infinity,
            cacheSize: 512,
            visible: false,
            properties: {
                id: entry.id,
                title: entry.name ?? entry.id,
            },
        });
        
        console.log(`buildRasterLayer: Successfully created ${entry.id}`);
        return layer;
    } catch (err) {
        console.error(`buildRasterLayer: ERROR creating ${entry.id}:`, err);
        throw err;
    }
}

export async function createOLMap() {
    // If the manifest can't be loaded (missing file, bad JSON, etc.) fall
    // back to an empty layer list rather than blowing up the whole app.
    let manifest = [];
    try {
        manifest = await fetchLayersManifest();
    } catch (err) {
        console.warn("2D layers manifest could not be loaded; starting with no raster layers.", err);
    }

    const rasterLayers = manifest.map(buildRasterLayer);

    // Simple mode: only one raster layer visible at a time. Default to the
    // first one in the manifest, if there is one.
    if (rasterLayers.length > 0) {
        rasterLayers[0].setVisible(true);
    }

    // Layer for any drawn points, lines, etc.
    const drawingSource = new VectorSource();
    const drawingLayer = new VectorLayer({
        source: drawingSource,
        properties: {
            id: 'drawings',
        },
    });


    // Map

    const map2d = new Map({
        target: 'map-2d',

        layers: [
            ...rasterLayers, // raster layers on the bottom
            drawingLayer,    // drawn features stay on top
        ],

        view: new View({
            center: fromLonLat([14.5058, 46.0569]),
            zoom: 15,
        }),
    });


    // Enforces "only one visible at a time": turns the chosen layer on and
    // every other raster layer off. See the note in layerControls.js for how
    // to relax this to multiple simultaneous layers.
    function setActiveLayer(id) {
        console.log(`setActiveLayer called with id: ${id}`);
        rasterLayers.forEach((layer) => {
            const layerId = layer.get('id');
            const shouldBeVisible = layerId === id;
            const currentlyVisible = layer.getVisible();
            console.log(`  Layer "${layerId}": currentlyVisible=${currentlyVisible}, shouldBeVisible=${shouldBeVisible}`);
            layer.setVisible(shouldBeVisible);
            console.log(`  Layer "${layerId}": now visible=${layer.getVisible()}`);
        });
    }

    console.log(map2d.getView().getProjection().getCode());
    console.log(map2d.getLayers().getArray());

    return { map: map2d, rasterLayers, setActiveLayer };
};